VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFunc"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Explicit





'Public Function Exec(ParamArray args_()) As Variant
'
'End Function

Public Function ExecMax06( _
 _
    Optional arg0_, Optional arg1_, Optional arg2_, Optional arg3_, Optional arg4_, Optional arg5_ _
 _
) As Variant
Attribute ExecMax06.VB_UserMemId = 0
    
End Function

Public Function xExec00() As Variant
    
End Function

Public Function xExec01(arg0_) As Variant
    
End Function

Public Function xExec02(arg0_, arg1_) As Variant
    
End Function

Public Function xExec03(arg0_, arg1_, arg2_) As Variant
    
End Function

Public Function xExec04(arg0_, arg1_, arg2_, arg3_) As Variant
    
End Function

Public Function xExec05(arg0_, arg1_, arg2_, arg3_, arg4_) As Variant
    
End Function
'
'Public Function xExec06(arg0_, arg1_, arg2_, arg3_, arg4_, arg5_) As Variant
'
'End Function
'
'Public Function xExec07(arg0_, arg1_, arg2_, arg3_, arg4_, arg5_, arg6_) As Variant
'
'End Function
'
'Public Function xExec08(arg0_, arg1_, arg2_, arg3_, arg4_, arg5_, arg6_, arg7_) As Variant
'
'End Function
'
'Public Function xExec09(arg0_, arg1_, arg2_, arg3_, arg4_, arg5_, arg6_, arg7_, arg8_) As Variant
'
'End Function
'
'Public Function xExec10(arg0_, arg1_, arg2_, arg3_, arg4_, arg5_, arg6_, arg7_, arg8_, arg9_) As Variant
'
'End Function
'
'
'
'




